sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t haonguyen858585/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true haonguyen858585/docker-react npm run test